CREATE DATABASE IF NOT EXISTS avaliacao_tecnica
  DEFAULT CHARACTER SET = utf8mb4
  DEFAULT COLLATE = utf8mb4_unicode_ci;
USE avaliacao_tecnica;

CREATE TABLE IF NOT EXISTS paises (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  populacao BIGINT DEFAULT 0,
  regiao VARCHAR(100) DEFAULT 'Desconhecida',
  bandeira VARCHAR(512),
  lingua VARCHAR(512),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_nome (nome)
);

CREATE TABLE IF NOT EXISTS avaliacoes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pais_id INT NOT NULL,
  curtidas INT DEFAULT 0,
  nao_curtidas INT DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pais_id) REFERENCES paises(id) ON DELETE CASCADE,
  UNIQUE KEY uniq_pais (pais_id)
);
